### ISSUE TITLE
Work on Windows 10

### ISSUE THREAD

**Issue by grayswandyr** [grayswandyr/electrod#4]
Check and possibly fix working on Windows 10. 

As we do not own any machine running W10, any help will be appreciated.

**Comment by LauraPanizo** [comment]
Hi! I' interested in using electrum on windows (10 or older version) thus, I need electrod running on windows too.
I have installed OCaml for windows but it fails when installing the ppxfind package. I have the same issue  when installing electrod on Ubuntu.

**Comment by grayswandyr** [comment]
Hi
thanks Laura! We don't have easy access to Windows-equipped machines so would you be willing to help in checking that we can indeed provide Windows users with Electrum.
What version of OCaml do you have? Could you paste the console output of installation on Ubuntu and Windows?

**Comment by LauraPanizo** [comment]
Hi David,
In Ubunt 18.04.3 LTS (running on virtual box) OCaml version in 4.05.0. I have tried multiple installations and currently only the last two package are pending. In windows 10, I have installed the OCaml for windows using the [64bit graphical installer ](https://fdopen.github.io/opam-repository-mingw/installation/). I experienced the same problems in both OS. 
The  console output is the following:

![Screenshot from 2020-07-02 09-29-42](https://user-images.githubusercontent.com/26867710/86329899-26ed3080-bc47-11ea-9fef-f4870abf9aa3.png)



Currently, I'm installing a newer version of ppxfind (v 1.3) on windows. I let you know if I'm able to finish the installation and run Electrum.

**Comment by grayswandyr** [comment]
I'm surprised to see this version for ppxfind. Would you try `opam update && opam upgrade` first?

**Comment by LauraPanizo** [comment]
Yes, I tried these commands first in windows and ubuntu.
I have not run electrum yet, but the installation in windows has finished!
As intermediate step, I installed autoconf in the cygwin (included in OCaml) to let opam install package conf-autconf.

**Comment by grayswandyr** [comment]
So IIUC, you were able to compile electrod, right?

**Comment by LauraPanizo** [comment]
Yes, it compiled and  it is recognized as a command from OCaml terminal. However, electrum does not load electrod, and I cannot run electrum from Ocaml terminal.
I supposse that the problem is in windows environment variables, but I don't know what to include in PATH or Library variables, any clue? I will try this afternoon again.

**Comment by grayswandyr** [comment]
No sorry, I haven't used Microsoft products for more than 15 years... Keep me informed!

**Comment by LauraPanizo** [comment]
Hi, 
I finally found the electrod executable and included in the PATH.
In order to load electrod and NuSMV, it is mandatory to remove file extension (.exe) because electrum is looking for files without extension.

Now, when I run the example of the leader election using NuSMV there is an exception.  I'm not sure if you could help me in this issue, or if it is better to open an issue in electrum github. Anyway, here is the stack trace:

class edu.mit.csail.sdg.alloy4.ErrorFatal: Unknown exception occurred: kodkod.engine.AbortedException: Electrod problem generation failed.
edu.mit.csail.sdg.translator.TranslateAlloyToKodkod.execute_commandFromBook(TranslateAlloyToKodkod.java:617)
edu.mit.csail.sdg.alloy4whole.SimpleReporter$SimpleTask1.run(SimpleReporter.java:705)
edu.mit.csail.sdg.alloy4.WorkerEngine.runLocally(WorkerEngine.java:227)
edu.mit.csail.sdg.alloy4whole.SimpleGUI.doRun(SimpleGUI.java:1190)
edu.mit.csail.sdg.alloy4whole.SimpleGUI.doExecuteLatest(SimpleGUI.java:1255)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
edu.mit.csail.sdg.alloy4whole.SimpleGUI$3.run(SimpleGUI.java:513)
edu.mit.csail.sdg.alloy4.Runner.actionPerformed(Runner.java:66)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)
caused by...
class kodkod.engine.AbortedException: Electrod problem generation failed.
kodkod.engine.ElectrodSolver.go(ElectrodSolver.java:202)
kodkod.engine.ElectrodSolver.access$3(ElectrodSolver.java:179)
kodkod.engine.ElectrodSolver$SolutionIterator.next(ElectrodSolver.java:147)
kodkod.engine.ElectrodSolver$SolutionIterator.next(ElectrodSolver.java:1)
edu.mit.csail.sdg.translator.A4Solution$Peeker.<init>(A4Solution.java:1244)
edu.mit.csail.sdg.translator.A4Solution$Peeker.<init>(A4Solution.java:1240)
edu.mit.csail.sdg.translator.A4Solution.solve(A4Solution.java:1616)
edu.mit.csail.sdg.translator.TranslateAlloyToKodkod.execute_commandFromBook(TranslateAlloyToKodkod.java:605)
edu.mit.csail.sdg.alloy4whole.SimpleReporter$SimpleTask1.run(SimpleReporter.java:705)
edu.mit.csail.sdg.alloy4.WorkerEngine.runLocally(WorkerEngine.java:227)
edu.mit.csail.sdg.alloy4whole.SimpleGUI.doRun(SimpleGUI.java:1190)
edu.mit.csail.sdg.alloy4whole.SimpleGUI.doExecuteLatest(SimpleGUI.java:1255)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
edu.mit.csail.sdg.alloy4whole.SimpleGUI$3.run(SimpleGUI.java:513)
edu.mit.csail.sdg.alloy4.Runner.actionPerformed(Runner.java:66)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)
caused by...
class java.io.FileNotFoundException: C:\Users\laura\AppData\Local\Temp\C:\Users\laura\DriveUMA\Docencia_2019_2020\MétodosFormales\Ideas\tutorial-Check_Liveness2_for_3_but_1..20_Time-2020-07-02-13-28-1742472909\00000.elo (El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos)
java.io.FileOutputStream.open0(Native Method)
java.io.FileOutputStream.open(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
java.io.PrintWriter.<init>(Unknown Source)
kodkod.engine.ElectrodSolver.go(ElectrodSolver.java:196)
kodkod.engine.ElectrodSolver.access$3(ElectrodSolver.java:179)
kodkod.engine.ElectrodSolver$SolutionIterator.next(ElectrodSolver.java:147)
kodkod.engine.ElectrodSolver$SolutionIterator.next(ElectrodSolver.java:1)
edu.mit.csail.sdg.translator.A4Solution$Peeker.<init>(A4Solution.java:1244)
edu.mit.csail.sdg.translator.A4Solution$Peeker.<init>(A4Solution.java:1240)
edu.mit.csail.sdg.translator.A4Solution.solve(A4Solution.java:1616)
edu.mit.csail.sdg.translator.TranslateAlloyToKodkod.execute_commandFromBook(TranslateAlloyToKodkod.java:605)
edu.mit.csail.sdg.alloy4whole.SimpleReporter$SimpleTask1.run(SimpleReporter.java:705)
edu.mit.csail.sdg.alloy4.WorkerEngine.runLocally(WorkerEngine.java:227)
edu.mit.csail.sdg.alloy4whole.SimpleGUI.doRun(SimpleGUI.java:1190)
edu.mit.csail.sdg.alloy4whole.SimpleGUI.doExecuteLatest(SimpleGUI.java:1255)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
edu.mit.csail.sdg.alloy4whole.SimpleGUI$3.run(SimpleGUI.java:513)
edu.mit.csail.sdg.alloy4.Runner.actionPerformed(Runner.java:66)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

**Comment by grayswandyr** [comment]
Thanks, cool.

Among the trace, I can see this line:
  class java.io.FileNotFoundException: 
C:\Users\laura\AppData\Local\Temp\C:\Users\laura\DriveUMA\Docencia_2019_2020\MétodosFormales\Ideas\tutorial-Check_Liveness2_for_3_but_1..20_Time-2020-07-02-13-28-1742472909\00000.elo 
(El nombre de archivo, el nombre de directorio o la sintaxis de la 
etiqueta del volumen no son correctos)

So indeed I think it comes from the Electrun2 side. Would you file an 
issue there? Pinging @nmacedo too.

**Comment by LauraPanizo** [comment]
Hi David,
I open an issue in Electrum2 github. Meanwhile, I have manually run electrod from command line using the test files.
I have used the default script for NuSMV unbounded model checking. The command line is as follows:
`electrod -s script_nusmv -t NuSMV -v test1.elo`
And it returns the following output with errors:

![SharedScreenshot](https://user-images.githubusercontent.com/26867710/86454631-ced62d00-bd1f-11ea-8246-de83ec753ef4.jpg)

**Comment by grayswandyr** [comment]
Hi Laura. 
Thanks for the report. I think this error is specific to Windows, I suppose the output of NuSMV is not the same as on Linux. Can you help me checking that? To do so, I'd need to see the NuSMV output.

1. Run `electrod --kg --na test1.elo` (this will tell you that it creates an SMV and an SCR files, that will not be removed)
1. Run `NuSM -source thescrfile.scr thesmffile.smv`
1. Paste the output here (as text rather than an image, please).

**Comment by LauraPanizo** [comment]
Hi, 
I supposse that steps 2 refers to NuSMV instead of NuSM. The output is pretty short:
```
unknown command 'check_ltlspec_ic3'
aborting 'source electrod-b32346.scr'
```

I downloaded the NuSMV v2.6.0 binaries for windows, it included two executables files (NuSMV and ltl2smv) and both are in the path. Should I install some extra tool or library for NuSMV?

I have checked the same using nuXmv and it seems it works....although I don't know what is checked in test1 :D
-- no proof or counterexample found with bound 4
-- no proof or counterexample found with bound 5
-- LTL specification TRUE  is true

**Comment by grayswandyr** [comment]
Yeah sorry I forgot one option:

1. is: `electrod.exe -t NuSMV --kg --na test1.elo`
2. `NuSMV -source thescrfile.scr thesmffile.smv`

Thank you.

**Comment by LauraPanizo** [comment]
Ok, so with the -t NuSMV option in step1, the step 2 returns that the specification is true:

********   WARNING   ********
The initial states set of the finite state machine is empty.
This might make results of model checking not trustable.
******** END WARNING ********
-- specification TRUE  is true

So, maybe the problem is the script file. I copied the one show in the help:

```
set default_trace_plugin 1;
set on_failure_script_quits 1;
read_model;
flatten_hierarchy;
encode_variables;
build_model;
check_ltlspec;
quit -x
```

Is it possible that the script is outdated?

**Comment by grayswandyr** [comment]
I don't think so... However, the script file to be used is the one generated in step 1.  For instance, this what I get:
```
electrod (C) 2016-2020 ONERA (development version)
[W004] test/test1.elo:25.24-25.25: keyword "disj" ignored as "s" is a single variable
       some disj x,y : r, disj s: x | true;
Keeping the script and SMV files at:
  test/electrod-8994bc.scr    <-- THIS IS THE SCR FILE
  test/test1.elo-a4c7ba.smv
```

In any case, notice that test files do not test model checking. They are only here to test the parser and other internal functions. You should rather look in `test/case-studies` or `regression` to find "real" .elo files.

**Comment by LauraPanizo** [comment]
You are right, the src file is exactly the same as the default script. Running the original command with the -s <sourcefile> produces the same uncaught exception.

In addition, I have tried a pair of test file in `test\case-studies` using the two steps options and that are the outputs:

chord-correctness-4.elo
```
file chord-correctness-4.elo: line 1: at token "univ": unexpected expression encountered during parsing
aborting 'source electrod-66be68.scr'
```

firewire-goodsafety-3.elo

```
-- specification  G (((!V-a & !V-b) & !V-c) | (((V-c & (!V-b & !V-a)) | (V-b & (!V-c & !V-a))) | (V-a & (!V-c & !V-b))))  is true
```

**Comment by grayswandyr** [comment]
Thanks for your report and help. (Un)fortunately, I cannot reproduce these issues under Linux. I'll try to get access to a Windows machine to investigate in more detail but it may take a little bit of time, sorry about that...

**Comment by grayswandyr** [comment]
Hi @LauraPanizo, in principle, the issue should be fixed as of  in https://github.com/grayswandyr/electrod/commit/ff6b5981d0f6dfe99f17a744b58670b332f813ff so it should work now. 

We will soon add this to the Electrum/Alloy 6 JAR distribution (@nmacedo).
